test(vercel workflow): fix deployment build error

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -4,6 +4,7 @@ env:
   BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
+  PREVIEW_URL: null
 
 on:
   pull_request:
@@ -11,95 +12,92 @@ on:
 
 jobs:
   preview-deployment:
+    timeout-minutes: 5
     runs-on: ubuntu-latest
-    outputs:
-      url: ${{ steps.get-url.outputs.test }}
     steps:
       - uses: actions/checkout@v4
       - name: Install dependencies
-        run: npm install -g pnpm
-      - name: Install Vercel CLI
-        run: npm install --global vercel@latest
-      - name: Pull Vercel Environment Information
-        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
-      # - name: Build Project Artifacts
-      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
-      - id: get-url
-        name: Deploy Project Artifacts to Vercel
+        #   run: npm install -g pnpm
+        # - name: Install Vercel CLI
+        #   run: npm install --global vercel@latest
+        # - name: Pull Vercel Environment Information
+        #   run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
+        # # - name: Build Project Artifacts
+        # #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
+        # - id: get-url
+        #   name: Deploy Project Artifacts to Vercel
+        #   run: |
+        #     # deployment_url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
+        #     deployment_url="https://wave-research-8m1fgx0vo-waverd.vercel.app"
+        #     deployment_hostname=${deployment_url#*://}
+        #     deployment_url_ref=$(echo "$deployment_url" | awk -F'-' '{print $3}')
+        #     # intended_alias_hostname=$(echo "${{ vars.SERVER_URL }}" | sed 's~^[a-zA-Z]*://~~') # remove https
+        #     intended_alias_hostname="${deployment_url_ref}${BASE_DOMAIN}"
+
+        #     deployment_id=$(curl -s -G \
+        #       -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
+        #       "https://api.vercel.com/v6/deployments/$deployment_hostname" | jq -r '.id')
+
+        #     echo "Deployment ID: $deployment_id"
+        #     echo "Deployment URL: $deployment_hostname"
+        #     echo "Deployment URL Ref: $deployment_url_ref"
+        #     echo "Intended Alias: $intended_alias_hostname"
+
+        #     if [ -z "$deployment_id" ]; then
+        #       echo "Failed to retrieve deployment ID. Exiting..."
+        #       exit 1
+        #     fi
+
+        #     current_alias_hostname=$(curl -s -G \
+        #       -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
+        #       "https://api.vercel.com/v4/aliases/$intended_alias_hostname?projectId=$VERCEL_PROJECT_ID&teamId=$VERCEL_ORG_ID" | jq -r '.alias')
+
+        #     if [[ "$current_alias_hostname" == "$intended_alias_hostname" ]]; then
+        #       vercel alias rm $intended_alias_hostname --token=${{ secrets.VERCEL_TOKEN }} --yes
+        #     fi
+
+        #     echo "Current Alias: $current_alias_hostname"
+
+        #     ALIAS_RESPONSE=$(curl --location --globoff \
+        #       -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
+        #       "https://api.vercel.com/v2/deployments/$deployment_id/aliases?teamId=${{ secrets.VERCEL_ORG_ID }}" \
+        #       --header "Content-Type: application/json" \
+        #       --data "{\"alias\": \"$intended_alias_hostname\"}")
+
+        #     echo "Alias Response: $ALIAS_RESPONSE"
+
+        #     # Verify Alias Set
+        #     if echo "$ALIAS_RESPONSE" | grep -q '"error"'; then
+        #       echo "Failed to set alias. Response: $ALIAS_RESPONSE"
+        #       exit 1
+        #     fi
+
+        #     echo "Alias set successfully for deployment: $deployment_id"
+        #     echo "PREVIEW_URL=$intended_alias_hostname" >> $GITHUB_ENV
+
         run: |
-          # deployment_url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
-          deployment_url="https://wave-research-8m1fgx0vo-waverd.vercel.app"
-          deployment_hostname=${deployment_url#*://}
-          deployment_url_ref=$(echo "$deployment_url" | awk -F'-' '{print $3}')
-          # intended_alias_hostname=$(echo "${{ vars.SERVER_URL }}" | sed 's~^[a-zA-Z]*://~~') # remove https
-          intended_alias_hostname="${deployment_url_ref}${BASE_DOMAIN}"
-
-          deployment_id=$(curl -s -G \
-            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
-            "https://api.vercel.com/v6/deployments/$deployment_hostname" | jq -r '.id')
-
-          echo "Deployment ID: $deployment_id"
-          echo "Deployment URL: $deployment_hostname"
-          echo "Deployment URL Ref: $deployment_url_ref"
-          echo "Intended Alias: $intended_alias_hostname"
-
-          if [ -z "$deployment_id" ]; then
-            echo "Failed to retrieve deployment ID. Exiting..."
-            exit 1
-          fi
-
-          current_alias_hostname=$(curl -s -G \
-            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
-            "https://api.vercel.com/v4/aliases/$intended_alias_hostname?projectId=$VERCEL_PROJECT_ID&teamId=$VERCEL_ORG_ID" | jq -r '.alias')
-
-          if [[ "$current_alias_hostname" == "$intended_alias_hostname" ]]; then
-            vercel alias rm $intended_alias_hostname --token=${{ secrets.VERCEL_TOKEN }} --yes
-          fi
-            
-            
-          echo "Current Alias: $current_alias_hostname"
-            
-          ALIAS_RESPONSE=$(curl --location --globoff \
-            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
-            "https://api.vercel.com/v2/deployments/$deployment_id/aliases?teamId=${{ secrets.VERCEL_ORG_ID }}" \
-            --header "Content-Type: application/json" \
-            --data "{\"alias\": \"$intended_alias_hostname\"}")
-
-          echo "Alias Response: $ALIAS_RESPONSE"
-
-          # Verify Alias Set
-          if echo "$ALIAS_RESPONSE" | grep -q '"error"'; then
-            echo "Failed to set alias. Response: $ALIAS_RESPONSE"
-            exit 1
-          fi
-
-          echo "Alias set successfully for deployment: $deployment_id"
-          echo "url=$intended_alias_hostname" >> "$GITHUB_OUTPUT"
+          intended_alias_hostname="8m1fgx0vo.waverd.com"
+          echo "PREVIEW_URL=$intended_alias_hostname" >> $GITHUB_ENV
 
   playwright-tests:
+    timeout-minutes: 5
     runs-on: ubuntu-latest
-    outputs:
-      url: ${{ needs.preview-deployment.outputs.url }}
     needs: preview-deployment
     steps:
-      - env:
-          PREVIEW_URL: ${{needs.preview-deployment.outputs.url}}
-        run: |
-          echo "Playwright test - BASE_URL:  $PREVIEW_URL"
-        timeout-minutes: 60
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
           node-version: lts/*
       - name: Install dependencies
         run: npm install -g pnpm && pnpm install
-
       - name: Install Playwright Browsers
         # run: pnpm exec playwright install --with-deps
         run: npx playwright install --with-deps chromium
 
       - name: Run test #Wait for deployment to complete and run Playwright tests
         run: |
+          echo "PREVIEW_URL: $PREVIEW_URL"
+          echo "Playwright test - BASE_URL - $PREVIEW_URL"
           npx wait-on https://$PREVIEW_URL && PREVIEW_URL=https://$PREVIEW_URL npx playwright test
         env:
           NODE_ENV: preview
@@ -112,13 +110,13 @@ jobs:
           retention-days: 30
 
   post-playwright-tests:
+    timeout-minutes: 3
     runs-on: ubuntu-latest
     needs: playwright-tests
     steps:
-      - env:
-          PREVIEW_URL: ${{needs.playwright-tests.outputs.url}}
-        run: echo "PREVIEW_URL $PREVIEW_URL"
-      #   timeout-minutes: 1
+      - name: Delete Vercel Domain Alias
+        run: |
+          echo "PREVIEW_URL $PREVIEW_URL"
       # - id: delete-preview-url
       #   run: |
       #     vercel alias rm $PREVIEW_URL --token=${{ secrets.VERCEL_TOKEN }} --yes
