test(vercel workflow): fix deployment build error

diff --git a/.github/workflows/preview.yaml b/.github/workflows/preview.yaml
--- a/.github/workflows/preview.yaml
+++ b/.github/workflows/preview.yaml
@@ -18,8 +18,6 @@ jobs:
         run: npm install --global vercel@latest
       - name: Pull Vercel Environment Information
         run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
-      # - name: delete alias
-      #   run: vercel alias rm preview.waverd.com --token=${{ secrets.VERCEL_TOKEN }} --yes
       # - name: Build Project Artifacts
       #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
       - name: Deploy Project Artifacts to Vercel
@@ -39,17 +37,27 @@ jobs:
           echo "Deployment ID: $deployment_id"
 
           if [ -z "$deployment_id" ]; then
-          echo "Failed to retrieve deployment ID. Exiting..."
-          exit 1
+            echo "Failed to retrieve deployment ID. Exiting..."
+            exit 1
           fi
-            
+
+          # Set Alias for the Deployment
+          current_alias_hostname=$(curl -s -G \
+          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
+          "https://api.vercel.com/v4/aliases/$intended_alias_hostname?projectId=$VERCEL_PROJECT_ID&teamId=$VERCEL_ORG_ID" | jq -r '.alias')
+
+          if [[ "$current_alias_hostname" == "$intended_alias_hostname" ]]; then
+            vercel alias rm preview.waverd.com --token=${{ secrets.VERCEL_TOKEN }} --yes
+          fi
+
+          echo "Current Alias: $current_alias_hostname"
+
           # Set Alias for the Deployment
           ALIAS_RESPONSE=$(curl --location --globoff \
             -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
             "https://api.vercel.com/v2/deployments/$deployment_id/aliases?teamId=${{ secrets.VERCEL_ORG_ID }}" \
             --header "Content-Type: application/json" \
             --data "{\"alias\": \"$intended_alias_hostname\"}")
-
 
           echo "Alias Response: $ALIAS_RESPONSE"
 
